# .github/workflows/main.yml

name: Generate and Deploy Weather Map

# ▼ このワークフローを実行するタイミング
on:
  # 1. スケジュール実行：UTCの0時, 6時, 12時, 18時に実行 (日本時間では9時, 15時, 21時, 翌3時)
  schedule:
    - cron: '0 */6 * * *'
  # 2. 手動実行：GitHubのActionsタブから手動で動かすことも可能にする
  workflow_dispatch:

# ▼ 実行する具体的なお仕事内容
jobs:
  build-and-deploy:
    # 実行環境はUbuntuの最新版を使う
    runs-on: ubuntu-latest
    
    # 手順
    steps:
      # 1. リポジトリのコードを仮想環境にコピーする
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境を準備する
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 必要なライブラリをインストールする
      - name: Install dependencies
        run: |
          pip install requests xarray numpy scipy cartopy shapely plotly cfgrib
          # cfgribが内部で利用するライブラリもインストール
          sudo apt-get update && sudo apt-get install -y libeccodes-dev

      # 4. あなたのPythonスクリプトを実行してHTMLを生成する
      - name: Run the Python script to generate HTML
        # ★★★↓ここのファイル名をあなたのファイル名に変更してください↓★★★
        run: python GSM_500hPa_2D_Animation_HTML.py

      # 5. 生成されたHTMLをWebページとして公開する
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 公開するファイルが置かれているフォルダを指定（今回はルートディレクトリなので./）
          publish_dir: ./
